[main]
file_path = "./game/Default_D.xex_uncrypted_extended.xex_uncompressed.xex"
out_directory_path = "./out"
switch_table_file_path = "./switch/fable2.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x82CA2C00	
savegprlr_14_address = 0x82CA2BB0
restfpr_14_address = 0x82CA751C
savefpr_14_address = 0x82CA74D0
restvmx_14_address = 0x82FFFF68
savevmx_14_address = 0x82FFFCD0
restvmx_64_address = 0x82FFFFFC
savevmx_64_address = 0x82FFFD64
