[main]
file_path = "./game/Default_D.xex_uncrypted.xex"
out_directory_path = "./out"
switch_table_file_path = "./switch/fable2.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x822F3380
savegprlr_14_address = 0x822F3330
restfpr_14_address = 0x822F3F1C
savefpr_14_address = 0x822F3ED0
restvmx_14_address = 0x822F6CA8
savevmx_14_address = 0x822F6A10
restvmx_64_address = 0x822F6D3C
savevmx_64_address = 0x822F6AA4
longjmp_address = 0x831B6790
setjmp_address = 0x831B6AB0
