[main]
file_path = "./private/Default.xex"
out_directory_path = "./ppc"
switch_table_file_path = "SWA_switch_tables.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x82CA2C00	
savegprlr_14_address = 0x82CA2BB0
restfpr_14_address = 0x82CA751C
savefpr_14_address = 0x82CA74D0
restvmx_14_address = 0x82FFFF68
savevmx_14_address = 0x82FFFCD0
restvmx_64_address = 0x82FFFFFC
savevmx_64_address = 0x82FFFD64

longjmp_address = 0x832B25CC
setjmp_address = 0x82CAF478

invalid_instructions = [
    { data = 0x00000000, size = 4 }, # Padding
    { data = 0x832B25AC, size = 8 }, # C Specific Frame Handler
    { data = 0x831C8B50, size = 8 },
    { data = 0x832B34C4, size = 64 } # End of .text
    
]
