[main]
file_path = "./private/Default.xex"
out_directory_path = "./ppc"
switch_table_file_path = "SWA_switch_tables.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x82CA2C00	
savegprlr_14_address = 0x82CA2BB0
restfpr_14_address = 0x82CA751C
savefpr_14_address = 0x82CA74D0
restvmx_14_address = 0x82FFFF68
savevmx_14_address = 0x82FFFCD0
restvmx_64_address = 0x82FFFFFC
savevmx_64_address = 0x82FFFD64

longjmp_address = 0x832B25CC
setjmp_address = 0x82CAF478

functions = [
    { address = 0x831FBB90, size = 0x198 },
    { address = 0x8241BAA8, size = 0x11C },
    { address = 0x824B7E70, size = 0x68 },
    { address = 0x823A5A28, size = 0x124 },
    { address = 0x8222B3C8, size = 0xF4 },
    { address = 0x822D7EA0, size = 0xE8 },
    { address = 0x8242C5E0, size = 0x88 },
    { address = 0x8283FF98, size = 0xCC },
    { address = 0x82A2F3E8, size = 0x114 },
    { address = 0x8289FB40, size = 0x2C8 },
    { address = 0x82520C00, size = 0x6C },
    { address = 0x82415A20, size = 0x1B8 },
    { address = 0x82FE7850, size = 0x108 },
    { address = 0x82BE9680, size = 0xBEC },
    { address = 0x82D9E9F0, size = 0x78 },
    { address = 0x82C56828, size = 0x78 },
    { address = 0x822A2AB0, size = 0xEC },
    { address = 0x824CAC90, size = 0x158 },
    { address = 0x8217F250, size = 0xF0 },
    { address = 0x83046BE8, size = 0x114 },
    { address = 0x82D9E998, size = 0x54 },
    { address = 0x82B8F5E8, size = 0x128 },
    { address = 0x82E33B90, size = 0xB4 },
    { address = 0x824D2800, size = 0x7C },
    { address = 0x8259AF48, size = 0x7C },
    { address = 0x82A34680, size = 0x480 },
    { address = 0x82C9E878, size = 0x244 },
    { address = 0x82C89840, size = 0x1D8 },
    { address = 0x822D7DF8, size = 0xA4 },
    { address = 0x82C9A118, size = 0x244 },
    { address = 0x82D97090, size = 0x3FC },
    { address = 0x82C99CB8, size = 0x214 },
    { address = 0x82592C80, size = 0x84 },
    { address = 0x82C99ED0, size = 0x244 },
    { address = 0x82B809E8, size = 0x22C },
    { address = 0x822EAA98, size = 0x94 },
    { address = 0x82CA1E98, size = 0x1BC },
    { address = 0x826224B8, size = 0xAC },
    { address = 0x8272B2C0, size = 0x168 },
    { address = 0x82BC9B28, size = 0x128 },
    { address = 0x82B57148, size = 0x2E0 },
    { address = 0x82C97120, size = 0x94 },
    { address = 0x82D82B48, size = 0x19C },
    { address = 0x831FBAC8, size = 0x64 },
    { address = 0x822D7CB0, size = 0x74 },
    { address = 0x82BE0100, size = 0xA4 },
    { address = 0x8283A008, size = 0x84 },
    { address = 0x82C8D3F0, size = 0x314 },
    { address = 0x82C9DA98, size = 0x198 },
    { address = 0x82DE6750, size = 0xF4 },
    { address = 0x82771250, size = 0xA0 },
    { address = 0x822D7D58, size = 0x9C },
    { address = 0x82CA1A00, size = 0x114 },
    { address = 0x82622360, size = 0xC0 },
    { address = 0x82C8DAE8, size = 0xF8 },
    { address = 0x82C8C9F0, size = 0x150 },
    { address = 0x831B31B8, size = 0x78 },
    { address = 0x82B38270, size = 0x110 },
    { address = 0x82DE4C10, size = 0x1E8 },
    { address = 0x83095890, size = 0x110 },
    { address = 0x8299F668, size = 0x90 },
    { address = 0x827D30C0, size = 0x2E0 },
    { address = 0x824BDE60, size = 0xA8 },
    { address = 0x824063B0, size = 0xF0 },
    { address = 0x831FBB30, size = 0x5C },
    { address = 0x82BC8260, size = 0x7C },
    { address = 0x822E2304, size = 0x15D4 },
    { address = 0x82B8D010, size = 0xF8C },
    { address = 0x8310FC68, size = 0x80 },
    { address = 0x82DA60B0, size = 0x31C },
    { address = 0x82E0F3A8, size = 0xCC },
    { address = 0x822D7C50, size = 0x5C },
    { address = 0x82522E18, size = 0x174 },
    { address = 0x82C9D280, size = 0x198 },
    { address = 0x831FBA60, size = 0x68 },
    { address = 0x825A0B58, size = 0x90 },
    { address = 0x82C8D708, size = 0x190 },
    { address = 0x82C8CF00, size = 0x100 },
    { address = 0x82C9B420, size = 0x274 },
    { address = 0x8250B778, size = 0x58 },
    { address = 0x82DDC208, size = 0x24C },
    { address = 0x831FBD28, size = 0x16C },
    { address = 0x82D7F5B0, size = 0x154 }
]

invalid_instructions = [
    { data = 0x00000000, size = 4 }, # Padding
    { data = 0x832B25AC, size = 8 }, # C Specific Frame Handler
    { data = 0x831C8B50, size = 8 },
    { data = 0x832B34C4, size = 64 } # End of .text
    
]
