// Fable-2 - ReXGlue Recompiled Project
// Generated by: rexglue init

#include "generated/Fable-2_config.h"
#include "generated/Fable-2_init.h"

#include <rex/filesystem.h>
#include <rex/runtime.h>
#include <rex/logging.h>
#include <rex/runtime/guest/function.h>
#include <rex/kernel/xthread.h>
#include <rex/graphics/graphics_system.h>
#include <rex/ui/window.h>
#include <rex/ui/window_listener.h>
#include <rex/ui/windowed_app.h>

#include <filesystem>
#include <thread>

class Fable2App : public rex::ui::WindowedApp, public rex::ui::WindowListener {
public:
    static std::unique_ptr<rex::ui::WindowedApp> Create(rex::ui::WindowedAppContext& ctx) {
        return std::make_unique<Fable2App>(ctx);
    }

    Fable2App(rex::ui::WindowedAppContext& ctx)
        : WindowedApp(ctx, "Fable2", "[game_directory]") {
        AddPositionalOption("game_directory");
    }

    bool OnInitialize() override {
        auto exe_dir = rex::filesystem::GetExecutableFolder();

        // Game directory: arg or default to exe_dir/assets
        std::filesystem::path game_dir;
        if (auto arg = GetArgument("game_directory")) {
            game_dir = *arg;
        } else {
            game_dir = exe_dir / "assets";
        }

        // Initialize logging
        auto log_file = exe_dir / "Fable2.log";
        rex::InitLogging(log_file.string().c_str(), spdlog::level::debug);
        REXLOG_INFO("Fable2 starting");
        REXLOG_INFO("  Game directory: {}", game_dir.string());

        // Create and initialize runtime
        runtime_ = std::make_unique<rex::Runtime>(".", game_dir);
        runtime_->set_app_context(&app_context());

        auto status = runtime_->Setup(
            static_cast<uint32_t>(PPC_CODE_BASE),
            static_cast<uint32_t>(PPC_CODE_SIZE),
            static_cast<uint32_t>(PPC_IMAGE_BASE),
            static_cast<uint32_t>(PPC_IMAGE_SIZE),
            PPCFuncMappings);
        if (XFAILED(status)) {
            REXLOG_ERROR("Runtime setup failed: {:08X}", status);
            return false;
        }

        // Load XEX image
        status = runtime_->LoadXexImage("game:\\default.xex");
        if (XFAILED(status)) {
            REXLOG_ERROR("Failed to load XEX: {:08X}", status);
            return false;
        }

        // Create window
        window_ = rex::ui::Window::Create(app_context(), "Fable-2", 1280, 720);
        if (!window_) {
            REXLOG_ERROR("Failed to create window");
            return false;
        }

        // Connect graphics presenter
        auto* graphics_system = runtime_->graphics_system();
        if (graphics_system && graphics_system->presenter()) {
            window_->SetPresenter(graphics_system->presenter());
        }

        window_->AddListener(this);
        window_->Open();

        // Launch module in background
        app_context().CallInUIThreadDeferred([this]() {
            auto main_thread = runtime_->LaunchModule();
            if (!main_thread) {
                REXLOG_ERROR("Failed to launch module");
                app_context().QuitFromUIThread();
                return;
            }

            std::thread([this, main_thread = std::move(main_thread)]() mutable {
                main_thread->Wait(0, 0, 0, nullptr);
                REXLOG_INFO("Execution complete");
                app_context().CallInUIThread([this]() {
                    app_context().QuitFromUIThread();
                });
            }).detach();
        });

        return true;
    }

    void OnClosing(rex::ui::UIEvent& e) override {
        (void)e;
        REXLOG_INFO("Window closing, shutting down...");
        app_context().QuitFromUIThread();
    }

    void OnDestroy() override {
        if (window_) {
            window_->RemoveListener(this);
        }
        window_.reset();
        runtime_.reset();
    }

private:
    std::unique_ptr<rex::Runtime> runtime_;
    std::unique_ptr<rex::ui::Window> window_;
};

XE_DEFINE_WINDOWED_APP(Fable-2, Fable2App::Create)

GUEST_FUNCTION_STUB(__imp__XamShowGamerCardUIForXUID);
GUEST_FUNCTION_STUB(__imp__XamShowAchievementsUI);
GUEST_FUNCTION_STUB(__imp__XamShowMarketplaceUI);
GUEST_FUNCTION_STUB(__imp__IoInvalidDeviceRequest);
GUEST_FUNCTION_STUB(__imp__ObReferenceObject);
GUEST_FUNCTION_STUB(__imp__IoDeleteDevice);
GUEST_FUNCTION_STUB(__imp__IoCompleteRequest);
GUEST_FUNCTION_STUB(__imp__RtlUpcaseUnicodeChar);
GUEST_FUNCTION_STUB(__imp__ObIsTitleObject);
GUEST_FUNCTION_STUB(__imp__IoCheckShareAccess);
GUEST_FUNCTION_STUB(__imp__IoRemoveShareAccess);
GUEST_FUNCTION_STUB(__imp__XNetLogonGetTitleID);
GUEST_FUNCTION_STUB(__imp__NetDll_WSAGetOverlappedResult);
GUEST_FUNCTION_STUB(__imp__NetDll_XNetRegisterKey);
GUEST_FUNCTION_STUB(__imp__NetDll_XNetUnregisterKey);
GUEST_FUNCTION_STUB(__imp__NetDll_XNetUnregisterInAddr);
GUEST_FUNCTION_STUB(__imp__NetDll_XNetConnect);
GUEST_FUNCTION_STUB(__imp__NetDll_XNetGetConnectStatus);
GUEST_FUNCTION_STUB(__imp__IoSetShareAccess);
GUEST_FUNCTION_STUB(__imp__XamUserGetMembershipTierFromXUID);
GUEST_FUNCTION_STUB(__imp__XamUserGetOnlineCountryFromXUID);
GUEST_FUNCTION_STUB(__imp__XamVoiceSubmitPacket);

